### ISSUE TITLE
leimaau_jyutping.dict.yaml里修订了一些粤拼错误

### ISSUE THREAD

**Issue by gkovacs** [leimaau/leimaau_jyutping#1]
https://github.com/gkovacs/fcitx-rime-config/commit/117d6be46351e958304de8344d1ac6a48eb25f05

**Comment by gkovacs** [comment]
还找到了另外两个粤拼错误 

https://github.com/gkovacs/fcitx-rime-config/commit/7823bbdbe9b419eada7df40658f57de7f91df082

**Comment by gkovacs** [comment]
https://github.com/gkovacs/fcitx-rime-config/commit/482605889ebe7a2235d753ecc1f780c49838ce92

**Comment by leimaau** [comment]
非常感谢指正，稍后修正后会更新
