### ISSUE TITLE
詞組一義多字形

### ISSUE THREAD

**Issue by wonghouwing** [leimaau/leimaau_jyutping#2]
粗略䁽咗一下 見到dict中詞條有「說服」同「説服」、「說法」同「説法」、「雪茄菸」同「雪茄煙」等一義多字形問題，而「說到尾」又只有一種字形，建議詞條只保留一種字形，以免喺默認模式(唔強制轉換某地區字形)下出現一義多選項情況

**Comment by leimaau** [comment]
多謝建議。箇問題我一早有留意過，都恁過轉換啲字形，但後來偷懶就放棄嘞，好似有好多字要改，可能要寫個py處理。另外個原因呢，顯示多啲方便研究性使用，因爲爾箇項目旨在我思考一啲問題時能夠打出多啲字形，多啲讀音，就算生僻字和音，越多就越能爲我解決問題帶來啓發。因此字形嘅唯一性就唔係我優先考慮嘅問題，甚至各地字形轉換都係一個大概轉換，做唔到嚴格轉換。雖然話到底係我懶，最後重係多謝你嘅建議。
